---
repos:
  # General pre-commits
  # - repo: https://github.com/pre-commit/pre-commit-hooks

  # Markdown files (.md)
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args:
          - "--config=.markdownlint.yaml"

  # Yaml files (.yaml|.yml)
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
        args:
          - "--config-file=.markdownlint.yaml"
          - "--strict"

  # Python files (.py)
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args:
          - "--config=pyproject.toml"

  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args:
          - "--config=pyproject.toml"

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args:
          - "--config=pyproject.toml"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--settings-file=pyproject.toml"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.5
    hooks:
      - id: pylint
        args:
          - "--rcfile pyproject.toml"

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        args:
          - "--config=pyproject.toml"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args:
          - "--py310-plus"
